(in-package :cl-info)
(let (
(deffn-defvr-pairs '(
; CONTENT: (<INDEX TOPIC> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS> <NODE NAME>))
("np_cvode" . ("numerics-sundials.info" 2604 46 "Function np_cvode f vars y0 tspan"))
("np_cvode <1>" . ("numerics-sundials.info" 2889 104 "Function np_cvode f vars y0 tspan rtol atol method events max_steps rootdir"))
("np_cvode <2>" . ("numerics-sundials.info" 3259 45 "Function np_cvode f_func y0 tspan"))
("np_cvode <3>" . ("numerics-sundials.info" 3536 86 "Function np_cvode f_func y0 tspan rtol atol method max_steps"))
("np_cvode_close" . ("numerics-sundials.info" 4667 40 "Function np_cvode_close handle"))
("np_cvode_create" . ("numerics-sundials.info" 3859 55 "Function np_cvode_create f vars y0 t0 ..."))
("np_cvode_reinit" . ("numerics-sundials.info" 4392 55 "Function np_cvode_reinit handle t_new y_new"))
("np_cvode_step" . ("numerics-sundials.info" 4134 49 "Function np_cvode_step handle t_target"))
("np_cvode_with_handle" . ("numerics-sundials.info" 4875 2653 "Function np_cvode_with_handle create_args body_fn"))
))
(section-pairs '(
; CONTENT: (<NODE NAME> . (<FILENAME> <BYTE OFFSET> <LENGTH IN CHARACTERS>))
("Definitions for numerics-sundials" . ("numerics-sundials.info" 1873 534))
("Introduction" . ("numerics-sundials.info" 607 626))
)))
(load-info-hashtables (maxima::maxima-load-pathname-directory) deffn-defvr-pairs section-pairs))
